version: '3.8'

services:
  db:
    #!!ระวังเรื่อง tap
    image: mysql:8.0 # ปรับเป็น MySQL 8.0 เพื่อความทันสมัย (หรือใช้ 5.7 ตามเดิมได้หากต้องการ)
    container_name: mysql_db_821
    # MySQL 8.0 ใช้ plugin ตัวใหม่ จึงต้องใช้คำสั่งนี้เพื่อให้เข้ากับ Client รุ่นเก่าได้ดีขึ้น
    #container ต้องตรงกัน!!
    command: --default-authentication-plugin=mysql_native_password
    environment: #ตัวแปรที่จะเข้าในฐานข้อมูล
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb
    ports: 
      - "8821:3306"
    volumes: #พท.เก็บฐานข้อมูล
      - mysql_data_821:/var/lib/mysql
    networks:
      - weblab821
    restart: always

  phpmyadmin: #tool ที่ใช้เข้าถึงฐานข้อมูล
    image: phpmyadmin:latest
    container_name: phpmyadmin_821
    environment:
      PMA_HOST: db # ใช้ชื่อ Service "db" แทนชื่อ Container เพื่อความยืดหยุ่นในระบบ Network
      PMA_PORT: 3306 #this port
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 64M # เพิ่มลิมิตการอัปโหลดไฟล์ SQL
    ports:
      - "8822:80" #ต้องไม่เหมือนกับข้างบน!
    depends_on: 
      - db
    networks: #networksที่เชื่อมถึงกัน
      - weblab821
    restart: always
#การ create
networks:
  weblab821:
    driver: bridge #ชื่อ networks

volumes:
  mysql_data_821: 
    driver: local